version: '3'
services:
  app:
    build: .
    ports:
      - '3003:3003'
    command: npm run dev -p 3003
    # Hot Reloadする
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - /app/node_modules
